options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: node:18
    id: Build Frontend
    dir: frontend
    entrypoint: bash
    args:
      - -c
      - |
        npm install
        npm run build

  - name: python:3.10
    id: Install Backend Dependencies
    dir: backend
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt

  - name: gcr.io/cloud-builders/rsync
    id: Deploy Frontend
    args:
      - -avz
      - ./frontend/dist/
      - /var/www/astrology-saas/frontend/dist/

  - name: gcr.io/cloud-builders/gcloud
    id: Restart Services
    entrypoint: bash
    args:
      - -c
      - |
        sudo systemctl restart nginx
        sudo systemctl restart frontend
        sudo systemctl restart backend

timeout: 1200s
