options:
  logging: CLOUD_LOGGING_ONLY  # Ensures logs are sent to Cloud Logging

steps:
  # Step 1: Install dependencies and build the frontend
  - name: node:18
    id: Build Frontend
    dir: frontend
    entrypoint: bash
    args:
      - -c
      - |
        npm install
        npm run build

  # Step 2: Install backend dependencies
  - name: python:3.10
    id: Install Backend Dependencies
    dir: backend
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt

  # Step 3: Deploy frontend to the server directory
  - name: gcr.io/cloud-builders/rsync
    id: Deploy Frontend
    args:
      - -avz
      - ./frontend/dist/
      - /var/www/astrology-saas/frontend/dist/

  # Step 4: Restart services (Nginx & backend)
  - name: gcr.io/cloud-builders/gcloud
    id: Restart Services
    entrypoint: bash
    args:
      - -c
      - |
        sudo systemctl restart nginx
        sudo systemctl restart backend
        sudo systemctl restart frontend

timeout: "1200s"
